display_name: Music
packager: Amphi
packagerEmail: support@amphi.site
url: https://amphi.site
license: GPLv3

icon: assets/logo/icon_512x512.png

keywords:
  - Music

generic_name: Music Player
summary: Cross-platform music player with support for syncing libraries via a self-hosted server
group: Applications/Multimedia

categories:
  - AudioVideo
  - Music
  - Player

startup_notify: false

metainfo: linux/packaging/music.appdata.xml