display_name: Music
package_name: amphi-music
maintainer:
  name: Amphi
  email: support@amphi.site
priority: optional
section: x11
installed_size: 45000
essential: false
icon: assets/logo/icon_512x512.png

postinstall_scripts:
  - echo "Installed Amphi Music successfully"
postuninstall_scripts:
  - echo "Uninstalled Amphi Music successfully"

keywords:
  - Music

generic_name: Music Player

categories:
  - AudioVideo
  - Music
  - Player

startup_notify: false